### ISSUE TITLE
Add link to docker installation

### ISSUE THREAD

**Issue by Vourhey** [airalab/home-assistant-web3-build#9]
In the requirements section it's not obvious the docker must be installed. Since it's assumed the host system is Ubuntu, let's add a link to a docker installation instruction

I would suggest the official one https://docs.docker.com/engine/install/ubuntu/ 
or the one from DigitalOcean https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-22-04

**Comment by nakata5321** [comment]
Updated readme in [new release](https://github.com/airalab/home-assistant-web3-build/releases/tag/v0.0.4)
